name: josephs_vs_01
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  google_fonts: ^7.0.0

  # Local storage
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.6.0

  # Images
  image_picker: ^1.0.7
  image_cropper: ^7.0.5
  file_picker: ^8.0.0

  # Dates
  intl: ^0.20.2

  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  url_launcher: ^6.3.2
  flutter_native_timezone: ^2.0.0

  #Voice recording (speech to text)
  speech_to_text: ^6.6.2
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_24pt-Bold.ttf
          weight: 700

    - family: Abel
      fonts:
        - asset: assets/fonts/Abel/Abel-Regular.ttf
          weight: 400

  assets:
    - assets/images/

# App launcher icons (Android + iOS)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"
